name: Notify Slack

on:
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: windows-latest

    steps:
      - name: Send Notification to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          $headers = @{
            'Content-Type' = 'application/json'
          }
          $body = @{
            text = "QA Env ALC-4355 automation report as on 22nd October 2024. Report URL: <https://automation.lambdatest.com/share?shareId=0E1OQ7TUHD43WG399BH6P66PFA219ISTJZIG8CZ8FA5RNR83CIVARGXLVSQBSUZV&isThemeEnabled=true&themeVersion=v2>"
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $env:SLACK_WEBHOOK -Method Post -Headers $headers -Body $body
