name: Notify Slack

on:
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: windows-latest

    steps:
      - name: Send Notification to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          $headers = @{
            'Content-Type' = 'application/json'
          }
          $body = @{
            text = "QA Env Mobile Only automation report as on 4th October 2024. Report URL: <https://links.lambdatest.com/appautomation/EBBA04KUFB5J577HFFF2WEEOF3197ZESPVKUH8WJVPBVZ1TJX48NH1UT0G0TKXCW>"
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $env:SLACK_WEBHOOK -Method Post -Headers $headers -Body $body
