name: Notify Slack

on:
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: windows-latest

    steps:
      - name: Send Notification to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          $headers = @{
            'Content-Type' = 'application/json'
          }
          $body = @{
            text = "QA Env Mobile Only cases automation report as on 22nd October 2024. Build used is (PlasticBank_QA_20241017). Report URL: <https://links.lambdatest.com/appautomation/MU5EJD1ZFCYN13JX1UA3R2Q6IPXPLT1DWMO3WVP8AUXBDQJCP2QFGIFWIR6HXNPC>"
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $env:SLACK_WEBHOOK -Method Post -Headers $headers -Body $body
