name: Notify Slack

on:
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: windows-latest

    steps:
      - name: Send Notification to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          $headers = @{
            'Content-Type' = 'application/json'
          }
          $body = @{
            text = "QA Alchemy and Impact Hub Cases automation report as on 22nd October 2024. Report URL: <https://automation.lambdatest.com/share?shareId=KORG99FVHU6MOMVE24X9ZP3RP5Z6G2K1QIZH7AF33SW1Q9DCLKB1ZZ27GCNK8I3E&isThemeEnabled=true&themeVersion=v2>"
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $env:SLACK_WEBHOOK -Method Post -Headers $headers -Body $body
